even_list = {
   "resource":"/users",
   "path":"/users",
   "httpMethod":"GET",
   "headers":{
      "Accept":"*/*",
      "Accept-Encoding":"gzip, deflate, br",
      "Cache-Control":"no-cache",
      "CloudFront-Forwarded-Proto":"https",
      "CloudFront-Is-Desktop-Viewer":"true",
      "CloudFront-Is-Mobile-Viewer":"false",
      "CloudFront-Is-SmartTV-Viewer":"false",
      "CloudFront-Is-Tablet-Viewer":"false",
      "CloudFront-Viewer-ASN":"197738",
      "CloudFront-Viewer-Country":"UA",
      "Host":"4z6vg7h9f9.execute-api.ca-central-1.amazonaws.com",
      "Postman-Token":"fae86da1-ab54-4583-b18d-b2657509f681",
      "User-Agent":"PostmanRuntime/7.31.1",
      "Via":"1.1 ba172beaa058835048fe52f15497da64.cloudfront.net (CloudFront)",
      "X-Amz-Cf-Id":"66HaY7cJu7-hpwkPzMoLZ3xPJDjElRl9E4in1u_88rHXBfTo4UssfA==",
      "X-Amzn-Trace-Id":"Root=1-63fde808-29a4832477fde4825bba9a71",
      "X-Forwarded-For":"176.97.63.98, 15.158.38.75",
      "X-Forwarded-Port":"443",
      "X-Forwarded-Proto":"https"
   },
   "multiValueHeaders":{
      "Accept":[
         "*/*"
      ],
      "Accept-Encoding":[
         "gzip, deflate, br"
      ],
      "Cache-Control":[
         "no-cache"
      ],
      "CloudFront-Forwarded-Proto":[
         "https"
      ],
      "CloudFront-Is-Desktop-Viewer":[
         "true"
      ],
      "CloudFront-Is-Mobile-Viewer":[
         "false"
      ],
      "CloudFront-Is-SmartTV-Viewer":[
         "false"
      ],
      "CloudFront-Is-Tablet-Viewer":[
         "false"
      ],
      "CloudFront-Viewer-ASN":[
         "197738"
      ],
      "CloudFront-Viewer-Country":[
         "UA"
      ],
      "Host":[
         "4z6vg7h9f9.execute-api.ca-central-1.amazonaws.com"
      ],
      "Postman-Token":[
         "fae86da1-ab54-4583-b18d-b2657509f681"
      ],
      "User-Agent":[
         "PostmanRuntime/7.31.1"
      ],
      "Via":[
         "1.1 ba172beaa058835048fe52f15497da64.cloudfront.net (CloudFront)"
      ],
      "X-Amz-Cf-Id":[
         "66HaY7cJu7-hpwkPzMoLZ3xPJDjElRl9E4in1u_88rHXBfTo4UssfA=="
      ],
      "X-Amzn-Trace-Id":[
         "Root=1-63fde808-29a4832477fde4825bba9a71"
      ],
      "X-Forwarded-For":[
         "176.97.63.98, 15.158.38.75"
      ],
      "X-Forwarded-Port":[
         "443"
      ],
      "X-Forwarded-Proto":[
         "https"
      ]
   },
   "queryStringParameters":"None",
   "multiValueQueryStringParameters":"None",
   "pathParameters":"None",
   "stageVariables":"None",
   "requestContext":{
      "resourceId":"26upba",
      "resourcePath":"/users",
      "httpMethod":"GET",
      "extendedRequestId":"BDExXFkJ4osFlQw=",
      "requestTime":"28/Feb/2023:11:39:52 +0000",
      "path":"/Dev/users",
      "accountId":"140294923654",
      "protocol":"HTTP/1.1",
      "stage":"Dev",
      "domainPrefix":"4z6vg7h9f9",
      "requestTimeEpoch":1677584392425,
      "requestId":"dd89ba84-817a-48b2-8c20-0025008102f7",
      "identity":{
         "cognitoIdentityPoolId":"None",
         "accountId":"None",
         "cognitoIdentityId":"None",
         "caller":"None",
         "sourceIp":"176.97.63.98",
         "principalOrgId":"None",
         "accessKey":"None",
         "cognitoAuthenticationType":"None",
         "cognitoAuthenticationProvider":"None",
         "userArn":"None",
         "userAgent":"PostmanRuntime/7.31.1",
         "user":"None"
      },
      "domainName":"4z6vg7h9f9.execute-api.ca-central-1.amazonaws.com",
      "apiId":"4z6vg7h9f9"
   },
   "body":"None",
   "isBase64Encoded": False
}

event_get_user = {
   "resource":"/users/{id}",
   "path":"/users/1",
   "httpMethod":"GET",
   "headers":{
      "Accept":"*/*",
      "Accept-Encoding":"gzip, deflate, br",
      "Cache-Control":"no-cache",
      "CloudFront-Forwarded-Proto":"https",
      "CloudFront-Is-Desktop-Viewer":"true",
      "CloudFront-Is-Mobile-Viewer":"false",
      "CloudFront-Is-SmartTV-Viewer":"false",
      "CloudFront-Is-Tablet-Viewer":"false",
      "CloudFront-Viewer-ASN":"197738",
      "CloudFront-Viewer-Country":"UA",
      "Host":"4z6vg7h9f9.execute-api.ca-central-1.amazonaws.com",
      "Postman-Token":"d509ec7b-9b55-40f0-8a95-c9be8559aa99",
      "User-Agent":"PostmanRuntime/7.31.1",
      "Via":"1.1 ba172beaa058835048fe52f15497da64.cloudfront.net (CloudFront)",
      "X-Amz-Cf-Id":"mscIdFb5Gyj_HFYDRK8VzNwjVDWX8GPMdtKLhvuf4qNhnt__oMeoXw==",
      "X-Amzn-Trace-Id":"Root=1-63fde819-21a9ee946f5e64a2186c5f6d",
      "X-Forwarded-For":"176.97.63.98, 15.158.38.75",
      "X-Forwarded-Port":"443",
      "X-Forwarded-Proto":"https"
   },
   "multiValueHeaders":{
      "Accept":[
         "*/*"
      ],
      "Accept-Encoding":[
         "gzip, deflate, br"
      ],
      "Cache-Control":[
         "no-cache"
      ],
      "CloudFront-Forwarded-Proto":[
         "https"
      ],
      "CloudFront-Is-Desktop-Viewer":[
         "true"
      ],
      "CloudFront-Is-Mobile-Viewer":[
         "false"
      ],
      "CloudFront-Is-SmartTV-Viewer":[
         "false"
      ],
      "CloudFront-Is-Tablet-Viewer":[
         "false"
      ],
      "CloudFront-Viewer-ASN":[
         "197738"
      ],
      "CloudFront-Viewer-Country":[
         "UA"
      ],
      "Host":[
         "4z6vg7h9f9.execute-api.ca-central-1.amazonaws.com"
      ],
      "Postman-Token":[
         "d509ec7b-9b55-40f0-8a95-c9be8559aa99"
      ],
      "User-Agent":[
         "PostmanRuntime/7.31.1"
      ],
      "Via":[
         "1.1 ba172beaa058835048fe52f15497da64.cloudfront.net (CloudFront)"
      ],
      "X-Amz-Cf-Id":[
         "mscIdFb5Gyj_HFYDRK8VzNwjVDWX8GPMdtKLhvuf4qNhnt__oMeoXw=="
      ],
      "X-Amzn-Trace-Id":[
         "Root=1-63fde819-21a9ee946f5e64a2186c5f6d"
      ],
      "X-Forwarded-For":[
         "176.97.63.98, 15.158.38.75"
      ],
      "X-Forwarded-Port":[
         "443"
      ],
      "X-Forwarded-Proto":[
         "https"
      ]
   },
   "queryStringParameters":"None",
   "multiValueQueryStringParameters":"None",
   "pathParameters":{
      "id":"1"
   },
   "stageVariables":"None",
   "requestContext":{
      "resourceId":"cegtur",
      "resourcePath":"/users/{id}",
      "httpMethod":"GET",
      "extendedRequestId":"BDE0FF3Z4osFzTQ=",
      "requestTime":"28/Feb/2023:11:40:09 +0000",
      "path":"/Dev/users/1",
      "accountId":"140294923654",
      "protocol":"HTTP/1.1",
      "stage":"Dev",
      "domainPrefix":"4z6vg7h9f9",
      "requestTimeEpoch":1677584409869,
      "requestId":"4d044b68-7a7f-431f-bc26-bbba702b4bdc",
      "identity":{
         "cognitoIdentityPoolId":"None",
         "accountId":"None",
         "cognitoIdentityId":"None",
         "caller":"None",
         "sourceIp":"176.97.63.98",
         "principalOrgId":"None",
         "accessKey":"None",
         "cognitoAuthenticationType":"None",
         "cognitoAuthenticationProvider":"None",
         "userArn":"None",
         "userAgent":"PostmanRuntime/7.31.1",
         "user":"None"
      },
      "domainName":"4z6vg7h9f9.execute-api.ca-central-1.amazonaws.com",
      "apiId":"4z6vg7h9f9"
   },
   "body":"None",
   "isBase64Encoded": False
}